runtime: custom
env: flex
automatic_scaling:
  min_num_instances: 1
  max_num_instances: 2
  cool_down_period_sec: 120
  cpu_utilization:
    target_utilization: 0.75
resources:
  cpu: 2
  memory_gb: 4
service: url-verification
